version: '3.7'

services:
  web:
    build: .
    ports:
      - "4000:4000" # In our .env file above, we chose port 4000
    env_file:
      - docker.env
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    volumes:
      - "./docker-compose-tmp/volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    env_file:
      - docker.env
